# Generated by Django 4.1.1 on 2022-11-02 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SCPEuclid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('title_object', models.CharField(max_length=255, verbose_name='Название объекта фонда')),
                ('description', models.CharField(max_length=6000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='scp_euclid/', verbose_name='Изображение')),
                ('content', models.CharField(max_length=5000, verbose_name='Условия содержания')),
            ],
            options={
                'verbose_name': 'Объект класса Евклид',
                'verbose_name_plural': 'Объекты класса Еклид',
                'ordering': ('title_object',),
            },
        ),
        migrations.CreateModel(
            name='SCPKeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('title_object', models.CharField(max_length=255, verbose_name='Название объекта фонда')),
                ('description', models.CharField(max_length=6000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='scp_keter', verbose_name='Изображение')),
                ('content', models.CharField(max_length=5000, verbose_name='Условия содержания')),
            ],
            options={
                'verbose_name': 'Объект класса Кетер',
                'verbose_name_plural': 'Объекты класса Кетер',
                'ordering': ('title_object',),
            },
        ),
        migrations.CreateModel(
            name='SCPSafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('title_object', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('description', models.CharField(max_length=6000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='scp_safe', verbose_name='Изображение')),
                ('content', models.CharField(max_length=5000, verbose_name='Условия содержания')),
            ],
            options={
                'verbose_name': 'Безопасный объект',
                'verbose_name_plural': 'Безопасные объекты',
                'ordering': ('title_object',),
            },
        ),
        migrations.CreateModel(
            name='SCPThaumiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('title_object', models.CharField(max_length=255, verbose_name='Название объекта фонда')),
                ('description', models.CharField(max_length=6000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='scp_thaumiel/', verbose_name='Изображение')),
                ('content', models.CharField(max_length=5000, verbose_name='Условия содержания')),
            ],
            options={
                'verbose_name': 'Объект класса таумиель',
                'verbose_name_plural': 'Объекты класса таумиель',
                'ordering': ('title_object',),
            },
        ),
        migrations.CreateModel(
            name='SCPAllClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('scp_euclid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scp_base.scpeuclid', verbose_name='Объект класса Евклид')),
                ('scp_keter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scp_base.scpketer', verbose_name='Объект класса Кетер')),
                ('scp_safe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scp_base.scpsafe', verbose_name='Объект класса Безопасный')),
                ('scp_thaumiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scp_base.scpthaumiel', verbose_name='Объект класса Таумиель')),
            ],
            options={
                'verbose_name': 'Все объекты фонда',
                'ordering': ('id',),
            },
        ),
    ]
