# Generated by Django 4.0.6 on 2022-12-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_scp', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
