# Generated by Django 4.0.6 on 2022-12-22 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_card_expirations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirations_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 21, 22, 9, 56, 842469), verbose_name='Срок годности'),
        ),
    ]
