# Generated by Django 4.0.6 on 2022-12-23 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_card_expirations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirations_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 22, 11, 56, 49, 514851), verbose_name='Срок годности'),
        ),
    ]
